#!/bin/bash

REGEX="[^0-9]*([0-9]+)[^0-9]*"
BRANCH_NAME=$(git symbolic-ref --short HEAD)

if [[ $BRANCH_NAME =~ $REGEX ]]; then
  BRANCH_NAME="DE-${BASH_REMATCH[1]}"
  BRANCH_IN_COMMIT=$(grep -c "$BRANCH_NAME" $1)

  if [ -n "$BRANCH_NAME" ] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then
    sed -i.bak -e "1s/^/$BRANCH_NAME /" $1
  fi
fi
